### ISSUE TITLE
Exception: unsupported locale setting in visualizzazione Dashboard

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#11]
Se si inizializza l'immagine in un sistema standard con la sola lingua inglese, la chiamata di: https://github.com/Sielte/rao-pubblico/blob/67546fb3e3b09ce3a5c30140450d1c02a5a9d8c0/rao/agency/utils/utils_db.py#L480
espone l'errore in oggetto, non trovando la localizzazione italiana.

Se nel Dockerfile si aggiunge `&& apt-get install -y locales locales-all \` e si settano le var
```
ENV LC_ALL it_IT.UTF-8
ENV LANG it_IT.UTF-8
ENV LANGUAGE it_IT.UTF-8
```
la dashboard visualizza i dati e i grafici.

**Comment by gianluca-difranco** [comment]
Buon pomeriggio,
con l'aggiornamento alla versione 1.0.3 di oggi la issue è stata risolta.
