### ISSUE TITLE
Regex id_card_issuer con nomi composti

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#12]
https://github.com/Sielte/rao-pubblico/blob/6e18b05451003b93ebe33ea3b1717ba33364ae57/rao/agency/classes/regex.py#L22

Questa regex genera errore in presenza di Comuni dal nome composto [San Vendemiano, Ronco Scrivia, etc...] nella funzione `clean_idCardIssuer`

https://github.com/Sielte/rao-pubblico/blob/9f934a811e97c90df6efed061d2c2f9aea20c9c2/rao/agency/forms.py#L672

**Comment by gianluca-difranco** [comment]
Buongiorno,
con [questo commit](https://github.com/Sielte/rao-pubblico/commit/606d152035061b11756f1efe54285a5e93f0b92b) il problema è stato risolto.

Grazie,
Gianluca
