### ISSUE TITLE
Errore invio email di verifica in fase di setup

### ISSUE THREAD

**Issue by lucnap** [Sielte/rao-pubblico#13]
Sto provando ad usare l'applicazione e durante la fase di setup mi da il seguente messaggio:
"Si è verificato un errore durante l'invio della mail di verifica, controlla che la configurazione SMTP sia corretta."

Ho controllato più volte la configurazione smtp ma da sempre lo stesso errore.
Ho avviato il container con -e MAIL_LOG_LEVEL="INFO" e anche con -e MAIL_LOG_LEVEL="ERROR"
Sono entrato nel container in esecuzione per cercare di capire qualcosa dai file di log ma non riesco a trovare il log delle email e nemmeno dell'applicazione.

L'account email l'ho testato con Mozilla Thunderbird e funziona tutto.
Mi potreste aiutare a capire cosa non va?

**Comment by rglauco** [comment]
Ciao, i log dell'applicazione si vedono da host con il comando `docker logs <nome_container>`, puoi usare l'opzione `-f` per vederli in tempo reale.

**Comment by lucnap** [comment]
Grazie Glauco, il problema stava nel formato del mittente, invece di inserire nel formato suggerito:
Comune di Roma <info@comune.it>
inserivo soltanto
Comune di Roma

Adesso funziona l'email ma ho un'altro problema che specifico in un nuovo thread.
