### ISSUE TITLE
Non trova nazioni.csv prefissi.csv ecc... ecc..

### ISSUE THREAD

**Issue by lucnap** [Sielte/rao-pubblico#14]
Il container docker restituisce i seguenti errori (dai log) nel momento in cui si conferma l'utente amministratore e si fa l'impostazione della password iniziale:

v. 1.0.4] [N.D.] [Pagani] [19/Jan/21 10:27:23] ERROR [init_nation] [agency.utils.utils_setup:50] Exception: [Errno 2] No such file or directory: 'data/nazioni.csv'
[v. 1.0.4] [N.D.] [Pagani] [19/Jan/21 10:27:23] ERROR [init_nation] [agency.utils.utils_setup:51] exception_value = [Errno 2] No such file or directory: 'data/nazioni.csv', value = <class 'type'         >
[v. 1.0.4] [N.D.] [Pagani] [19/Jan/21 10:27:24] ERROR [init_nation] [agency.utils.utils_setup:52] tb = ['Traceback (most recent call last):\n', '  File "/rao/agency/utils/utils_setup.py", line 3         5, in init_nation\n    with open(os.path.join(settings.DATA_FILES_PATH, file), encoding=\'utf-8\') as csv_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'data/nazioni.csv'\n"         ]

Come si vede sembra che non riesce a trovare i files, pur essendo presenti nella cartella interna al container /rao/data

Ho avviato il container con il seguente comando:
docker run -d \
       --name "raopubblico1" \
       -e SIGN_URL="http://151.151.151.151:8001/" \
       -e BASE_URL="http://151.151.151.151:8002/" \
       -e SECRET_KEY="123456" \
       -e DATABASE_NAME="/data/raopubblico1.sqlite3" \
       -e MAIL_LOG_LEVEL="WARNING" \
       -e AGENCY_LOG_LEVEL="INFO" \
       -e RAO_NAME="Roma" \
       --mount type=volume,source="voldatarao",target="/data" \
       -p "8002:8000" \
       "rao-app:latest"  "/start"

**Comment by rglauco** [comment]
Ho segnalato la cosa nell'[issue 3]( https://github.com/Sielte/rao-pubblico/issues/3), dove ho proposto una soluzione che risolve il problema.

**Comment by lucnap** [comment]
ho visto il tuo vecchio post, quindi il problema si risolve semplicemente passando un altra variabile d'ambiente DATA_FILES_PATH="/rao/data/"
Nel frattempo che gli sviluppatori non sistemano il problema

Grazie mille

**Comment by gianluca-difranco** [comment]
Buongiorno,
con [questo commit](https://github.com/Sielte/rao-pubblico/commit/fbdd1dc6063c6d9f184b4be144f308ff0135e960) la variabile presente su settings.py è stata modificata. 

Chiudo entrambe le issue.
