### ISSUE TITLE
Errori in funzioni di preselezione con nuova installazione ver. 1.0.8

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#16]
Le funzioni di preselezione seguenti:
- Prefisso internazione pre-popolato con '+39';
- Nazione di domicilio pre-popolato con 'Italia'.

restituiscono errore in caso di prima installazione con db non ancora inizializzato.
```
  File "/rao/rao/urls.py", line 7, in <module>
    from agency import views
  File "/rao/agency/views.py", line 21, in <module>
    from .forms import LoginForm, NewOperatorForm, NewIdentityForm, \
  File "/rao/agency/forms.py", line 414, in <module>
    class NewIdentityForm(Form):
  File "/rao/agency/forms.py", line 497, in NewIdentityForm
    initial=get_choices_prefix()[0],
IndexError: list index out of range
```
mentre non danno problemi in caso di aggiornamento del software da versioni precedenti.

**Comment by gianluca-difranco** [comment]
Con l'aggiornamento [1.0.9](https://github.com/Sielte/rao-pubblico/commit/5e0dbd90589482d330040f767cd67b424dfe78da) le funzionalità introdotte sono state corrette.
