### ISSUE TITLE
Dockerfile mancante

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#2]
Il Dockerfile ".compose/local/django/Dockerfile" non risulta disponibile nel repository [rao-pubblico-signer](https://github.com/Sielte/rao-pubblico-signer)

**Comment by fgugliuzza** [comment]
I file mancanti e una piccola fix della documentazione sono stati inseriti nel commit https://github.com/Sielte/rao-pubblico/commit/a7a0f82248ff028e7e3fc3258a3ef03da34fbe95.

[rao-pubblico-signer](https://github.com/Sielte/rao-pubblico-signer), invece, non ha un Dockerfile in quanto non è un progetto containerizzato.
