### ISSUE TITLE
ERRORE 500 "Errore durante il cambio pin"

### ISSUE THREAD

**Issue by Brignoli** [Sielte/rao-pubblico#21]
All'ultimo passaggio necessario per l'attivazione dell'account Amministrator, dopo aver inserito i dati del PIN di Firma temporaneo,
nuovo PIN di Firma con conferma, certificato e chiave privata e dato la conferma, appare l'errore:
 500 "Errore durante il cambio pin"

**Comment by Jessica-Chiara** [comment]
@Brignoli dovresti verificare dai log se il sistema di firma ti sta rispondendo in maniera corretta
