### ISSUE TITLE
Errore 500.  Con nel file LOG "Exception: UNIQUE constraint failed: api_user.username"

### ISSUE THREAD

**Issue by Brignoli** [Sielte/rao-pubblico#22]
interrogando il signer con questa stringa
curl -X POST -d "username=[codice fiscale tolto per privacy]&entity=c_m109" http://rao.comune:7000/v2/api/init
come risposta appare questa stringa
{"statusCode": 200, "message": "588604"}

Però, provando ad inserire il pin temporaneo nella pagina web di attivazione dell'account si riceve l'errore 500.

Nel file debug.log che si trova dentro il docker signer ci sono le seguenti righe:

[v. 1.0.0] [26/Apr/21 10:36:43] INFO [init] [api.views:42] SO: [codice fiscale tolto per privacy] Issuer: c_m109 Operazione eseguita correttamente
[v. 1.0.0] [26/Apr/21 10:51:06] ERROR [init] [api.views:45] Exception: UNIQUE constraint failed: api_user.username

Come poter proseguire correttamente?

**Comment by Jessica-Chiara** [comment]
L'eccezione scatenata è una violazione del vincolo di univocità sul campo _username_ della tabella _User_

Probabilmente sono stati inseriti più record che hanno lo stesso valore nel campo username. 
Prova a verificare dal DB @Brignoli attendo tue notizie per aiutarti a risolvere il problema

**Comment by Brignoli** [comment]
Nel file signer/db.sqlite3 ho trovato solo una occorrenza del codice fiscale [codice fiscale tolto per privacy]:

....
....
.... 
-AHM109_[codice fiscale tolto per privacy]_ 864060SYSTEM2021-04-26 07:41:46.983171ADMIN
��-	_[codice fiscale tolto per privacy_] 
��		C_M109
 �		
 T���b:
#      ���rN.

....
....
....
