### ISSUE TITLE
Template non corretto associato a recupero password

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#24]
In fase di recupero password, la funzione `send_recovery_link` restituisce errore `Exception: rao/mail/mail_recovery.html` perché non trova il template:
https://github.com/Sielte/rao-pubblico/blob/9df9d158136c144f55c1aeb06c29dbf241964de8/rao/agency/utils/utils_db.py#L236
Se si cambia con il nome del file presente in **rao/mail/** [mail_recovery_password.html](https://github.com/Sielte/rao-pubblico/blob/master/rao/templates/rao/mail/mail_recovery_password.html) (oppure in alternativa si rinomina il file) il recupero password funziona.

**Comment by gianluca-difranco** [comment]
Grazie della segnalazione, è stata rilasciata una nuova versione modificando il riferimento da lei indicato.

Gianluca
