### ISSUE TITLE
caricamento incompleto dei prefissi telefonici

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#25]
Vi segnalo che nel confronto tra nazioni.csv e prefissi.csv emergono differenze nella denominazione delle nazioni (usata come chiave di ricerca per il test di presenza) che implicano la mancata scrittura del prefisso nel DB.

Nel nostro caso il problema è emerso con un numero di cellulare russo:
https://github.com/Sielte/rao-pubblico/blob/c9377a69801992fc5e60082c729e5a34aa8b502f/rao/data/prefissi.csv#L184
https://github.com/Sielte/rao-pubblico/blob/c9377a69801992fc5e60082c729e5a34aa8b502f/rao/data/nazioni.csv#L31

Gurdando meglio ci sono altre difformità tra i due files csv, ne elenco alcune:
```
nazioni;prefissi
Zimbabwe;Zimbawe
Tagikistan;Tajikistan
Sudafrica;Sud Africa
Serbia&Montenegro;Serbia
San Marino;Repubblica di San Marino
Repubblica Ceca;Repubblica ceca
Macedonia del Nord;Macedonia
Monaco;Monaco Principato e Montecarlo
Costa Rica;Costarica
```

**Comment by gianluca-difranco** [comment]
Salve,
con la versione 1.0.14 abbiamo modificato il file dei prefissi così da far matchare un numero maggiore di nazioni. Sul file nazioni è stato modificato solo il nome di _Federazione russa_ in _Russia_.

Grazie per la segnalazione,
Buona giornata,
Gianluca
