### ISSUE TITLE
Cambio url elenco RAO Pubblici

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#26]
Nel sito Spid è cambiato [il link all'elenco delle PA che erogano il servizio RAO](https://www.spid.gov.it/cos-e-spid/come-attivare-spid/le-pa-per-attivare-spid/). I cittadini che cliccano il link nella mail a seguito dell'identificazione ottengono un 404.

Sarebbe opportuno riportare il nuovo link nei template del pdf e della mail:
https://github.com/Sielte/rao-pubblico/blob/796c478db8554fdb08591249b066de5d6a1b3001/rao/templates/rao/mail/mail_passphrase.html#L24

https://github.com/Sielte/rao-pubblico/blob/1347fea1aee9f096e60d177c035ba8c1ca84b117/rao/templates/rao/pdf/pdf_template.html#L52

Ho già fatto presente la necessità dell'attivazione di un redirect del vecchio url verso il nuovo.

**Comment by gianluca-difranco** [comment]
Buon pomeriggio,
Grazie mille per la segnalazione.
Abbiamo appena rilasciato una nuova versione con i link aggiornati.

Buona giornata,
Gianluca
