### ISSUE TITLE
Password SMTP non valida se troppo lunga

### ISSUE THREAD

**Issue by PierfrancescoElia** [Sielte/rao-pubblico#27]
Buongiorno,
segnalo il fatto che sia in fase di set-up iniziale che poi accedendo all'area Admin > Impostazioni, la password dell'account e-mail configurato, se troppo lunga (non ho modo di definire il _troppo_ in maniera precisa) non viene accettata dal sistema.

Ho provato in primo luogo con una api-key lunga 64 caratteri, e quindi con una password lunga 16 caratteri. La password da 16 caratteri ha funzionato, mentre l'api-key no.

Spero possiate presto correggere il problema.

Grazie, 
distinti saluti.

**Comment by gianluca-difranco** [comment]
Buongiorno @PierfrancescoElia,
Con la versione 1.0.15 è stato modificato il limite relativo alla lunghezza della password. 

Grazie mille della segnalazione,
Gianluca
