### ISSUE TITLE
Errore in fase di registrazione e-mail del cittadino da parte di addetto RAO

### ISSUE THREAD

**Issue by Umberto7** [Sielte/rao-pubblico#29]
Salve,

esiste una procedura che il RAO di uno SPID point può effettuare per poter modificare e/o cancellare i dati di un cittadino in caso di errore dopo averlo registrato? 

Ad esempio, se un addetto RAO, in fase di registrazione dati di un cittadino richiedente lo SPID, commette un errore di battitura nell'indicare l'indirizzo e-mail del cittadino o semplicemente gli viene fornita errata, la procedura viene ultimata, ma con l'e-mail del cittadino errata, per cui non è possibile procedere all'attivazione dello SPID, perché il cittadino non può ricevere la prima parte del codice di attivazione. L'addetto RAO, si accorge dell'errore commesso, ma non avendo la possibilità né di modificare, né di eliminare la richiesta errata, prova ad effettuare una nuova richiesta di registrazione, ma questa va in errore, perché provando a reinserire il nominativo, il caricamento va a buon fine, ma il codice che si riceve risulta errato.
Aggiungo che nemmeno l'utente amministratore ha la possibilità di modificare o eliminare la richiesta con l'e-mail errata.

**Comment by Jessica-Chiara** [comment]
Non esiste una procedura in quanto andrebbe rigenerato il pacchetto contenente i dati del cittadino (il rao in questa versione non tiene traccia dei dati del cittadino, immagazziniamo il minimo indispensabile). Un operatore dovrà rifare il pacchetto per intero ricompilando i dati. Comunque, non c'è alcun vincolo sul numero di identificazioni che si possono effettuare al cittadino. Naturalmente, su ogni intervento, la responsabilità dell'identificazione è dell'Operatore che esegue il riconoscimento de visu.
