### ISSUE TITLE
HTTPS self-signed per comunicazione cifrata

### ISSUE THREAD

**Issue by PierfrancescoElia** [Sielte/rao-pubblico#30]
Buongiorno,
vista l'importanza e la delicatezza dei dati, sarebbe fantastico (anche solo con un certificato autofirmato) che la comunicazione avvenisse con HTTPS, invece che con HTTP.

Sarebbe possibile implementarlo nelle prossime versioni?

Grazie e buon lavoro.

**Comment by Jessica-Chiara** [comment]
devi settare le configurazioni per come è giusto che sia, quindi se vuoi metterlo in https lo puoi fare sulle configurazioni del progetto. 
Il codice sorgente deve essere un esempio ma le configurazioni del tuo servizio le dovresti impostare tu
