### ISSUE TITLE
regex_rao_name errore con comuni che hanno l'apostrofo all'interno del nome

### ISSUE THREAD

**Issue by Umberto7** [Sielte/rao-pubblico#32]
rao-pubblico/rao/agency/classes/regex.py:

regex_rao_name = RegexValidator(
regex=r'^[A-Z]{1}[A-zÀ-ù ]{1,100}$',
message="Il primo carattere deve essere maiuscolo.")

Questa regex genera errore per i comuni che presentano nome con apostrofo.

**Comment by gianluca-difranco** [comment]
Buongiorno Umberto,
con la versione 1.0.16 il problema è stato risolto. Chiudo la Issue.

Grazie della segnalazione!
Gianluca
