### ISSUE TITLE
Avvio dell'applicativo

### ISSUE THREAD

**Issue by onorini-secoges** [Sielte/rao-pubblico#33]
Dopo aver seguito le istruzioni ed avviato il docker, non viene attivato alcun servizio sulla porta 8000, anche se apparentemente non vengono mostrati errori.

Riprovando con la versione rao-pubblico v. 1.0.14, il sistema si avvia correttamente.
Non ho ancora provato il corretto funzionamento di quest'ultimo.

**Comment by gianluca-difranco** [comment]
Buongiorno, 
invito a procedere come segue:

1. aggiornare il progetto all'ultima versione;
2. modificare la riga 28 del docker-compose nel seguente modo:
`      dockerfile: ./compose/local/sieltesign/Dockerfile`
3. seguire la guida come presentato nel readme. 

Se dovesse presentarsi il seguente errore:

`standard_init_linux.go:190: exec user process caused "no such file or directory"`

Bisogna utilizzare dostounix sui file entrypoint e start di signserver e rao ( o eventualmente aprirli con Notepad++ e passare al formato UNIX )
![image](https://user-images.githubusercontent.com/71270003/150118933-78b5c615-c695-43f0-a966-04e7390f7334.png)

e riavviare il tutto con il comando docker-compose up --build.

Lascio aperta la issue, nel caso tutto vada correttamente procederò aggiornando la versione con le modifiche sopra descritte.

Grazie per la segnalazione!
Gianluca

**Comment by onorini-secoges** [comment]
Grazie per la risposta, sembra che il problema fosse che i file start e entrypoint nelle rispettive cartelle, non avessero i permessi di esecuzione.
Impostati quelli, e rifatto il build, l'applicativo si è avviato correttamente
