### ISSUE TITLE
Possibile integrazione con i gestionali comunali

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#4]
Ho provato ad integrare il software con il gestionale comunale, relativamente al caricamento automatico dei dati di residenza e, se presenti, anche dell'indirizzo mail e del n. di cellulare, al fine di minimizzare l'inserimento manuale.
https://www.youtube.com/watch?v=Kvnt3M1YOOs

Pensate di standardizzare in futuro questa possibilità?

**Comment by Jessica-Chiara** [comment]
Si, lo possiamo fare quando sarà disponibile una API per ANPR. 
Che gestionale usa il Comune in questione?

**Comment by rglauco** [comment]
Nel Comune dove lavoro abbiamo Halley: tempo fa ho creato le API per gestire la comunicazione dei dati con IO e adesso le uso anche per recuperarli dal vostro software.

Volendo accedere ai soli dati di residenza ci sarebbero [le vecchie specifiche SAD](https://dait.interno.gov.it/documenti/manuale_tecnico_e_duso_sad_v2.8.pdf) che i software nei comuni hanno implementato per interfacciare l'applicazione web dedicata alla CIE.

**Comment by rglauco** [comment]
> 
> 
> Nel Comune dove lavoro abbiamo Halley: tempo fa ho creato le API per gestire la comunicazione dei dati con IO e adesso le uso anche per recuperarli dal vostro software.
> 
> Volendo accedere ai soli dati di residenza ci sarebbero [le vecchie specifiche SAD](https://dait.interno.gov.it/documenti/manuale_tecnico_e_duso_sad_v2.8.pdf) che i software nei comuni hanno implementato per interfacciare l'applicazione web dedicata alla CIE. [le cito solo per completezza]

Ho fatto un veloce test di implementazione e il sistema funziona correttamente anche con questa interfaccia. Purtroppo l'indirizzo mail e il recapito telefonico non sono acquisibili.

L'assunto è che il servizio rao sia installato localmente, oppure che l'istanza cloud del gestionale esponga il servizio SAD. Giusto per condividere, lascio il sorgente se qualche collega volesse usarlo (e di sicuro migliorarne la qualità...)
Per non incorrere in problemi di mappatura delle [DUG](https://registry.geodati.gov.it/dug) è opportuno desumere una lista completa delle denominazioni presenti nel db dello stradario e caricarla in choices.py.

In `settings.py`:
`SAD_URL = os.environ.get('SAD_URL', 'http://your-ip:port/user=<user>&password=<password>')`

in `utils.py`:

```
import xml.etree.ElementTree as ET
import requests

def sad_data(cf):
    """
    Ricerca dati di residenza nel db locale attraverso il servizio SAD locale
    :param cf: Codice fiscale
    :return: nome, cognome e dati di residenza
    """
    data = ''
    try:
        query='IDATIANAG.XML   62      FOTO.PNG       0       FIRMA.PNG      0       AD USO FUTURO  0       <Query><CodFiscale>'+cf+'</CodFiscale></Query>'
        response = requests.post(settings.SAD_URL,query)
        if(response.status_code==200):
            root = ET.fromstring(response.content)
            risultato=root[0][0].text #restituisce -1 in caso negativo, 1 in caso positivo
            if risultato=="1":
                data= {
                'cognome' :     root[1][0][0].text.strip(),
                'nome':         root[1][0][1].text.strip(),
                'dug':          root[1][0][8][0].text.strip().capitalize(), #prima lettera maiuscola per mapparlo con i valori enum di choices.py
                'indirizzo':    root[1][0][8][1].text.strip(),
                'nciv':         root[1][0][8][2].text.strip(),
                'cap':          root[1][0][8][3].text.strip()
                }
    except Exception as e:
        LOG.warning("Exception: {}".format(str(e)))
    return data
```
