### ISSUE TITLE
Invio token ad indirizzo PEC

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#5]
Nel caso in cui il cittadino presenti una PEC per registrarsi, potrebbe esserci un problema di invio del messaggio, in quanto sempre più spesso le caselle PEC vengono configurate per rifiutare i messaggi da mail ordinarie.

Per ovviare al potenziale problema, in area admin potrebbe essere implementata la configurazione di parametri di posta certificata, dove indicare il server PEC e le credenziali di accesso dell'Ente. Nel frontend si potrebbe pensare ad una checkbox "PEC" vicino ai campi mail, in modo da far utlizzare i parametri PEC per l'invio.

**Comment by gianluca-difranco** [comment]
Buongiorno,
durante la richiesta di identificazione, il cittadino è tenuto a fornire obbligatoriamente un indirizzo email (**non PEC**) e opzionalmente può fornire anche un indirizzo PEC. 

Al momento non è prevista questo tipo di modifica ma nulla vieta ai vari enti di lavorarci in maniera personale.

Grazie mille,
Gianluca
