### ISSUE TITLE
request.session['identified'] resta True in caso di nuovo inserimento

### ISSUE THREAD

**Issue by rglauco** [Sielte/rao-pubblico#8]
https://github.com/Sielte/rao-pubblico/blob/67546fb3e3b09ce3a5c30140450d1c02a5a9d8c0/rao/agency/views.py#L389

Sequenza per verificare il problema:

1. inserire una nuova richiesta fino a completare la procedura (download del PDF)
2. cliccare su "*Nuova richiesta*"
3. al momento dell'inserimento della richiesta, invece di vedere il `NewIdentityPinForm` si viene rediretti (302) sulla lista identità

Confrontando i due payload, la prima richiesta di identità (/agency/add_identity) presenta il campo 
`Content-Disposition: form-data; name="identifica" Identifica utente`, la seconda no.

Tracciando la variabile `request.session['identified']` nel punto indicato, alla seconda richiesta si presenta valorizzata `True` anzichè `False`.

Se invece l'operatore, dopo aver inserito la prima richiesta, clicca "*Lista richieste*" e successivamente "*Nuova richiesta*", il problema pare non porsi.

**Comment by gianluca-difranco** [comment]
Buongiorno, con la versione 1.0.3 che verrà rilasciata nei prossimi giorni, il problema di cui sopra sarà corretto.

Grazie mille,
Gianluca
