### ISSUE TITLE
Errore in fase Build

### ISSUE THREAD

**Issue by salvotrotta** [Sielte/rao-pubblico#9]
Provando a seguire tutti i passaggi indicati ovvero partendo dall'inserimento del comando:

`docker build --no-cache -f "./compose/local/django/Dockerfile" -t "rao-app:latest"`

mi restituisce l'errore `"docker build" requires exactly 1 argument`

Provando invece a utilizzare il comando `docker build --no-cache compose\local\django -t "rao-app:latest"` va ma comunque termina il processo con l'errore, in rosso:

```
New password: Password change aborted.
passwd: Authentication token manipulation error
passwd: password unchanged
Use of uninitialized value $answer in chop at /usr/sbin/adduser line 556.
Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 557.
```
Questo sia su Windows che su Linux

**Comment by rglauco** [comment]
Riguardo l'errore *"docker build" requires exactly 1 argument*, basta aggiungere un punto alla fine del comando: `docker build --no-cache -f "./compose/local/django/Dockerfile" -t "rao-app:latest" .`
